### ISSUE TITLE
Unit tests do not work

### ISSUE THREAD

**Issue by melchoir55** [mscharhag/blog-examples#2]
Not sure if this project is dead, but I found that your unit tests don't work. They throw an error:

java.lang.AssertionError: Sending request failed: Connection refused
from the following line:
at com.mscharhag.sparkdemo.UserControllerIntegrationTest.aNewUserShouldBeCreated(UserControllerIntegrationTest.java:31)

**Comment by hologup** [comment]
Yes it does not work for few ppl here either, even though they have some other changes..but the main change to connect to server fails..
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
